aws_sqs_queue_name = "rocket-project-prod-sqs-queue"
sns_topic_name     = "rocket-project-prod-sns-topic"
project_name       = "rocket-project"
environment        = "prod"
aws_region         = "sa-east-1"
