aws_sqs_queue_name = "rocket-project-dev-sqs-queue"
sns_topic_name     = "rocket-project-dev-sns-topic"
sns_topic_arn      = "arn:aws:sns:sa-east-1:063630845645:rocket-project-dev-sns-topic"
project_name       = "rocket-project"
environment        = "dev"
aws_region         = "sa-east-1"
